### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by chittaranjan870** [san4op/roundcube_cloud_button#1]
Dear,
I have used roundcube 1.4.9 and owncloud 10.0.10.
Bur after clicking cloud_button nothing is showing (showing black)

**Comment by chittaranjan870** [comment]
[ownCloud](https://owncloud.com/)

    App not installed:

ownCloud – A safe home for all your data

**Comment by chittaranjan870** [comment]
This is the WebDAV interface. It can only be accessed by WebDAV clients such as the ownCloud desktop sync client.

**Comment by san4op** [comment]
The plugin don't support WebDAV, just adds a button that open url (in new tab/window) specified in config.inc.php (link can points to anything web-interface: OwnCloud, iCloud, Google Drive etc.).
