### ISSUE TITLE
Failed to load plugin file 

### ISSUE THREAD

**Issue by maxtoor** [san4op/roundcube_cloud_button#2]
Plugin not loaded.
Log:
`PHP Error: Failed to load plugin file /var/www/roundcube/plugins/rc_custom_button/rc_custom_button.php in /var/www/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 193 (POST /?_task=mail&_action=refresh)`
Solution:
Rename custom_button.php to rc_custom_button.php
Rename class custom_button to rc_curtom_button in this file.
:)

**Comment by san4op** [comment]
Hello.
You are just using wrong plugin name in `$config['plugins']`. It should be `cloud_button`, and the plugin should be installed in `plugins/cloud_button` folder.

**Comment by maxtoor** [comment]
Hi and sorry,
the issue was about a fork called rc_custom_button. The issue link took me directly here and I didn't notice. Sorry again.
